app_web:
    resource: "@AppBundle/Controller/Web"
    type:     annotation

app_api:
    resource: "@AppBundle/Controller/API"
    type:     annotation
    defaults:
        _format: json


user_web:
    resource: "@UserBundle/Controller/Web"
    type:     annotation

user_api:
    resource: "@UserBundle/Controller/API"
    type:     annotation
    defaults:
        _format: json