parameters:

services:
    app.security.login_form_authenticator:
        class: UserBundle\Security\LoginFormAuthenticator
        autowire: true

    app.doctrine.hash_password.listener:
        class: UserBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber}

    jwt_token_authenticator:
          class: AppBundle\Security\JwtTokenAuthenticator
          autowire: true

    api.response_factory:
      class: AppBundle\Api\ResponseFactory
